wsc/forms.py
import wtforms
from wtforms import StringField
from wtforms.validators import DataRequired, Optional
from flask_ckeditor import CKEditorField
from models import Project


class ProjectEntry(wtforms.Form):

    title = StringField(
        'Title',
        validators=[DataRequired()])

    intro = CKEditorField(
        'Introduction',
        validators=[Optional()])

    scope = CKEditorField(
        'Scope',
        validators=[Optional()])

    org = CKEditorField(
        'Organization',
        validators=[Optional()])

    resp = CKEditorField(
        'Responsibilities',
        validators=[Optional()])

    facilities = CKEditorField(
        'Facilities',
        validators=[Optional()])

    labs = CKEditorField(
        'Laboratories',
        validators=[Optional()])

    dq_management = CKEditorField(
        'Data-Quality Management',
        validators=[Optional()])

    dq_planning = CKEditorField(
        'Data-Quality Planning',
        validators=[Optional()])

    dq_roles = CKEditorField(
        'Data-Quality Roles',
        validators=[Optional()])

    dq_workflows = CKEditorField(
        'Data-Quality Workflows',
        validators=[Optional()])

    dq_wf_pro = CKEditorField(
        'wf proposals',
        validators=[Optional()])

    dq_wf_workplan = CKEditorField(
        'wf workplans',
        validators=[Optional()])

    dq_wf_project_dmp = CKEditorField(
        'proj data management',
        validators=[Optional()])

    dq_wf_review = CKEditorField(
        'proj reviews',
        validators=[Optional()])

    dq_datasharing = CKEditorField(
        'Data Sharing Agreements',
        validators=[Optional()])

    dq_mous = CKEditorField(
        'Memoranda of Understands (MOUs)',
        validators=[Optional()])

    dq_access = CKEditorField(
        'Access Controls and Copyrights',
        validators=[Optional()])

    dq_aquisition = CKEditorField(
        'Data Acquisitions',
        validators=[Optional()])

    dq_aqu_roles = CKEditorField(
        'Data Acquisitions Roles',
        validators=[Optional()])

    dq_aqu_proc = CKEditorField(
        'Data Acquisitions Procedure',
        validators=[Optional()])

    dq_aqu_proc_coll = CKEditorField(
        'Data Acquisitions Collection Procedure',
        validators=[Optional()])

    dq_aqu_proc_proc = CKEditorField(
        'Data Acquisitions Processing Policies',
        validators=[Optional()])

    dq_aqu_proc_anal = CKEditorField(
        'Data Analysis and Policies',
        validators=[Optional()])

    dq_doc = CKEditorField(
        'Data Documentation',
        validators=[Optional()])

    dq_format = CKEditorField(
        'Data Formats',
        validators=[Optional()])

    dq_org = CKEditorField(
        'Organization of Files or Data',
        validators=[Optional()])

    dq_store = CKEditorField(
        'Data Storage',
        validators=[Optional()])

    dq_store_roles = CKEditorField(
        'Storage Roles',
        validators=[Optional()])

    dq_store_repo = CKEditorField(
        'Repositories',
        validators=[Optional()])

    dq_store_archive = CKEditorField(
        'Archiving',
        validators=[Optional()])

    dq_pubs = CKEditorField(
        'Publication and Sharing',
        validators=[Optional()])

    dq_pubs_roles = CKEditorField(
        'Publication Roles',
        validators=[Optional()])

    dq_pubs_workflow = CKEditorField(
        'Publication Workflow',
        validators=[Optional()])

    dq_pubs_prop = CKEditorField(
        'Publication Sensitive Data',
        validators=[Optional()])

    dq_pubs_release = CKEditorField(
        'Publication release',
        validators=[Optional()])

    dq_pubs_cite = CKEditorField(
        'Publication Citation',
        validators=[Optional()])

    dq_pubs_doi = CKEditorField(
        'Publication DOI',
        validators=[Optional()])

    dq_pubs_meta = CKEditorField(
        'Publication Meta',
        validators=[Optional()])

    dq_pubs_catalog = CKEditorField(
        'Publication Catalog',
        validators=[Optional()])

    qa_intro = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_field_data = CKEditorField(
        'Quality Assessment - Field Data',
        validators=[Optional()])

    qa_pro_ts = CKEditorField(
        'Quality Assessment - Time series Provisional',
        validators=[Optional()])

    qa_app_ts = CKEditorField(
        'Quality Assessment - Time Series Approved',
        validators=[Optional()])

    qa_discrete = CKEditorField(
        'Quality Assessment - Discrete Data Processing',
        validators=[Optional()])

    qa_db_integrity = CKEditorField(
        'Quality Assessment - Databases',
        validators=[Optional()])

    qa_records = CKEditorField(
        'Quality Assessment - records',
        validators=[Optional()])

    qa_interpretive = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_training = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_terms = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_resources = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])


    status = wtforms.SelectField(
        'Status',
        choices=(
            (Project.STATUS_DRAFT, "Save Draft"),
            (Project.STATUS_SUBMITTED, "Submit for Review")),
        coerce=int)

    def save_entry(self, Project):
        self.populate_obj(Project)
        Project.generate_slug()
        return Project


class ProjectApprove(wtforms.Form):

    title = StringField(
        'Title',
        validators=[DataRequired()])

    intro = CKEditorField(
        'Introduction',
        validators=[Optional()])

    scope = CKEditorField(
        'Scope',
        validators=[Optional()])

    org = CKEditorField(
        'Organization',
        validators=[Optional()])

    resp = CKEditorField(
        'Responsibilities',
        validators=[Optional()])

    facilities = CKEditorField(
        'Facilities',
        validators=[Optional()])

    labs = CKEditorField(
        'Laboratories',
        validators=[Optional()])

    dq_management = CKEditorField(
        'Data-Quality Management',
        validators=[Optional()])

    dq_planning = CKEditorField(
        'Data-Quality Planning',
        validators=[Optional()])

    dq_roles = CKEditorField(
        'Data-Quality Roles',
        validators=[Optional()])

    dq_workflows = CKEditorField(
        'Data-Quality Workflows',
        validators=[Optional()])

    dq_wf_pro = CKEditorField(
        'wf proposals',
        validators=[Optional()])

    dq_wf_workplan = CKEditorField(
        'wf workplans',
        validators=[Optional()])

    dq_wf_project_dmp = CKEditorField(
        'proj data management',
        validators=[Optional()])

    dq_wf_review = CKEditorField(
        'proj reviews',
        validators=[Optional()])

    dq_datasharing = CKEditorField(
        'Data Sharing Agreements',
        validators=[Optional()])

    dq_mous = CKEditorField(
        'Memoranda of Understands (MOUs)',
        validators=[Optional()])

    dq_access = CKEditorField(
        'Access Controls and Copyrights',
        validators=[Optional()])

    dq_aquisition = CKEditorField(
        'Data Acquisitions',
        validators=[Optional()])

    dq_aqu_roles = CKEditorField(
        'Data Acquisitions Roles',
        validators=[Optional()])

    dq_aqu_proc = CKEditorField(
        'Data Acquisitions Procedure',
        validators=[Optional()])

    dq_aqu_proc_coll = CKEditorField(
        'Data Acquisitions Collection Procedure',
        validators=[Optional()])

    dq_aqu_proc_proc = CKEditorField(
        'Data Acquisitions Processing Policies',
        validators=[Optional()])

    dq_aqu_proc_anal = CKEditorField(
        'Data Analysis and Policies',
        validators=[Optional()])

    dq_doc = CKEditorField(
        'Data Documentation',
        validators=[Optional()])

    dq_format = CKEditorField(
        'Data Formats',
        validators=[Optional()])

    dq_org = CKEditorField(
        'Organization of Files or Data',
        validators=[Optional()])

    dq_store = CKEditorField(
        'Data Storage',
        validators=[Optional()])

    dq_store_roles = CKEditorField(
        'Storage Roles',
        validators=[Optional()])

    dq_store_repo = CKEditorField(
        'Repositories',
        validators=[Optional()])

    dq_store_archive = CKEditorField(
        'Archiving',
        validators=[Optional()])

    dq_pubs = CKEditorField(
        'Publication and Sharing',
        validators=[Optional()])

    dq_pubs_roles = CKEditorField(
        'Publication Roles',
        validators=[Optional()])

    dq_pubs_workflow = CKEditorField(
        'Publication Workflow',
        validators=[Optional()])

    dq_pubs_prop = CKEditorField(
        'Publication Sensitive Data',
        validators=[Optional()])

    dq_pubs_release = CKEditorField(
        'Publication release',
        validators=[Optional()])

    dq_pubs_cite = CKEditorField(
        'Publication Citation',
        validators=[Optional()])

    dq_pubs_doi = CKEditorField(
        'Publication DOI',
        validators=[Optional()])

    dq_pubs_meta = CKEditorField(
        'Publication Meta',
        validators=[Optional()])

    dq_pubs_catalog = CKEditorField(
        'Publication Catalog',
        validators=[Optional()])

    qa_intro = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_field_data = CKEditorField(
        'Quality Assessment - Field Data',
        validators=[Optional()])

    qa_pro_ts = CKEditorField(
        'Quality Assessment - Time series Provisional',
        validators=[Optional()])

    qa_app_ts = CKEditorField(
        'Quality Assessment - Time Series Approved',
        validators=[Optional()])

wsc/blueprint.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from flask_login import login_required
from app import app, db
from models import Project, National, ACCESS, require_access
from wsc.forms import ProjectEntry, ProjectApprove

wsc = Blueprint('wsc', __name__, template_folder='templates')


def get_NatlReq():
    query = National.query.filter(National.id == 1).first_or_404()
    return query


NatlReq = get_NatlReq()


def object_list(template_name, query, **context):
    object_list = query
    return render_template(template_name, object_list=object_list, **context)


def plan_list(template, query, **context):
    valid_statuses = (Project.STATUS_APPROVED, Project.STATUS_DRAFT, Project.STATUS_SUBMITTED)
    query = query.filter(Project.status.in_(valid_statuses))
    if request.args.get('q'):
        search = request.args['q']
        query = query.filter(
            (Project.body.contains(search)) |
            (Project.title.contains(search)))
    return object_list(template, query, **context)


def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Project.status == Project.STATUS_APPROVED)
    else:
        # Allow user to view their own drafts.
        query = query.filter(
            (Project.status == Project.STATUS_APPROVED) |
            ((Project.author_id == g.user) & (Project.status != Project.STATUS_DELETED)))
        return query


def get_entry_or_404(slug, author=None):
    query = Project.query.filter(Project.slug == slug)
    return query.first_or_404()


@wsc.route('/')
def index():
    plans = Project.query.order_by(Project.created_timestamp.desc())
    return render_template('/wsc/index.html', plans=plans, National=NatlReq)


@wsc.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('wsc/detail.html', Project=entry, NationalRequired=NatlReq)


@wsc.route('/create/', methods=['GET', 'POST'])
@require_access(ACCESS['WSC'])
@login_required
def create():
    if request.method == 'POST':
        form = ProjectEntry(request.form)
        if form.validate():
            entry = form.save_entry(Project(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectEntry()

    return render_template('wsc/create.html', form=form, NationalRequired=NatlReq)


@wsc.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['WSC'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = ProjectEntry(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectEntry(obj=entry)

    return render_template('wsc/edit.html', Project=entry, form=form, NationalRequired=NatlReq)


@wsc.route('/<slug>/approve/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def approve(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = ProjectApprove(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectApprove(obj=entry)

    return render_template('wsc/approve.html', Project=entry, form=form, NationalRequired=NatlReq)

wsc/templates/wsc/detail.html
{% extends "base.html" %}

{% block title %}{{ Project.slug }}{% endblock %}

{% block content_title %}{{ Project.slug }}{% endblock %}



{% block content %}
<main>
  <div class="container pt-5">
      <div class="row pt-5">
      <!-- sidebar -->
      <div class="col-sm-3">
        <nav id="toc" data-toggle="toc" class="sticky-top">
          <h5 class="text-muted">Table of Contents</h5>
        </nav>
          <br>
        {% if current_user.user_level() > 0 %}
          <p><a href="{{ url_for('wsc.edit', slug=Project.slug)}}">Edit</a></p>
        {% endif %}
        {% if current_user.user_level() == 2 %}
          <p><a href="{{ url_for('wsc.approve', slug=Project.slug)}}">Approve</a></p>
        {% endif %}
      </div>
        <!-- main -->
     <div class="col-lg">
         <h1>{{ Project.title }}</h1>
        <h2><label>Introduction</label></h2>
            {{  NationalRequired.intro | safe }}
            <font color="red">{{ Project.intro | safe }}</font>

         <h2><label>Organization</label></h2>
            {{  NationalRequired.org  | safe}}
            <font color="red">{{ Project.org | safe }}</font>

         <h2><label>Responsibilities</label></h2>
            {{  NationalRequired.resp  | safe }}
            <font color="red">{{  Project.resp | safe }}</font>

         <h2><label>Facilities</label></h2>
            {{   NationalRequired.facilities | safe  }}
            <font color="red">{{ Project.facilities| safe }}</font>

         <h2><label>Laboratories</label></h2>
             {{   NationalRequired.labs | safe  }}
            <font color="red">{{ Project.labs| safe }}</font>

         <h2><label>Data-Quality Management</label></h2>
            {{   NationalRequired.dq_management | safe  }}
            <font color="red">{{ Project.dq_management| safe }}</font>

         <h3><label>Planning</label></h3>
            {{   NationalRequired.dq_planning | safe  }}
            <font color="red">{{ Project.dq_planning| safe }}</font>

         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_roles | safe  }}
            <font color="red">{{ Project.dq_roles| safe }}</font>

         <h4><label>Workflows</label></h4>
            {{   NationalRequired.dq_workflows | safe  }}
            <font color="red">{{ Project.dq_workflows| safe }}</font>

         <h5><label>Proposals</label></h5>
            {{   NationalRequired.dq_wf_pro | safe  }}
            <font color="red">{{ Project.dq_wf_pro| safe }}</font>

         <h5><label>Workplans</label></h5>
            {{   NationalRequired.dq_wf_workplan | safe  }}
            <font color="red">{{ Project.dq_wf_workplan| safe }}</font>

         <h5><label>Project Data Management Plans</label></h5>
            {{   NationalRequired.dq_wf_project_dmp | safe  }}
            <font color="red">{{ Project.dq_wf_project_dmp| safe }}</font>

         <h5><label>Project Reviews</label></h5>
            {{   NationalRequired.dq_wf_review | safe  }}
            <font color="red">{{ Project.dq_wf_review| safe }}</font>

         <h4><label>Data Sharing Agreements</label></h4>
            {{   NationalRequired.dq_datasharing | safe  }}
            <font color="red">{{ Project.dq_datasharing| safe }}</font>

         <h4><label>Memoranda of Understanding (MOUs)</label></h4>
            {{   NationalRequired.dq_mous | safe  }}
            <font color="red">{{ Project.dq_mous| safe }}</font>

         <h4><label>Access Controls/Copyright</label></h4>
            {{   NationalRequired.dq_access | safe  }}
            <font color="red">{{ Project.dq_access| safe }}</font>

         <h3><label>Data Acquisition, Processing and Analysis</label></h3>
            {{   NationalRequired.dq_aquisition | safe  }}
            <font color="red">{{ Project.dq_aquisition| safe }}</font>

         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_aqu_roles | safe  }}
            <font color="red">{{ Project.dq_aqu_roles| safe }}</font>

        <h4><label>Procedures and Methods</label></h4>
            {{   NationalRequired.dq_aqu_proc | safe  }}
            <font color="red">{{ Project.dq_aqu_proc| safe }}</font>

         <h5><label>Data Collection Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_coll | safe  }}
            <font color="red">{{ Project.dq_aqu_proc_coll| safe }}</font>

          <h5><label>Data Processing Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_proc | safe  }}
            <font color="red">{{ Project.dq_aqu_proc_proc| safe }}</font>

          <h5><label>Data Analysis Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_anal | safe  }}
            <font color="red">{{ Project.dq_aqu_proc_anal| safe }}</font>

          <h4><label>Documentation</label></h4>
            {{   NationalRequired.dq_doc | safe  }}
            <font color="red">{{ Project.dq_doc| safe }}</font>

         <h4><label>Data Formats</label></h4>
            {{   NationalRequired.dq_format | safe  }}
            <font color="red">{{ Project.dq_format| safe }}</font>

         <h4><label>Organization of Files/Data</label></h4>
            {{   NationalRequired.dq_org | safe  }}
            <font color="red">{{ Project.dq_org| safe }}</font>

         <h3><label>Data Preservation, Storage and Archive</label></h3>
            {{   NationalRequired.dq_store | safe  }}
            <font color="red">{{ Project.dq_store| safe }}</font>

         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_store_roles | safe  }}
            <font color="red">{{ Project.dq_store_roles| safe }}</font>

         <h4><label>Repositories</label></h4>
            {{   NationalRequired.dq_store_repo | safe  }}
            <font color="red">{{ Project.dq_store_repo| safe }}</font>

         <h4><label>Archiving</label></h4>
            {{   NationalRequired.dq_store_archive | safe  }}
            <font color="red">{{ Project.dq_store_archive| safe }}</font>

         <h3><label>Publication/Sharing</label></h3>
            {{   NationalRequired.dq_pubs | safe  }}
            <font color="red">{{ Project.dq_pubs| safe }}</font>

         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_pubs_roles | safe  }}
            <font color="red">{{ Project.dq_pubs_roles| safe }}</font>

         <h4><label>Workflow</label></h4>
            {{   NationalRequired.dq_pubs_workflow | safe  }}
            <font color="red">{{ Project.dq_pubs_workflow| safe }}</font>

         <h4><label>Proprietary and Sensitive Data</label></h4>
            {{   NationalRequired.dq_pubs_prop | safe  }}
            <font color="red">{{ Project.dq_pubs_prop| safe }}</font>

         <h4><label>Dissemination/Release</label></h4>
            {{   NationalRequired.dq_pubs_release | safe  }}
            <font color="red">{{ Project.dq_pubs_release| safe }}</font>

         <h4><label>Data Citation</label></h4>
            {{   NationalRequired.dq_pubs_cite | safe  }}
            <font color="red">{{ Project.dq_pubs_cite| safe }}</font>

         <h4><label>Digital Object Identifiers</label></h4>
            {{   NationalRequired.dq_pubs_doi | safe  }}
            <font color="red">{{ Project.dq_pubs_doi| safe }}</font>

         <h4><label>Metadata/Documentation</label></h4>
            {{   NationalRequired.dq_pubs_meta | safe  }}
            <font color="red">{{ Project.dq_pubs_meta| safe }}</font>

         <h4><label>Data Catalogs</label></h4>
            {{   NationalRequired.dq_pubs_catalog | safe  }}
            <font color="red">{{ Project.dq_pubs_catalog| safe }}</font>

         <h2><label>Quality Assessment</label></h2>
            {{   NationalRequired.qa_intro | safe  }}
            <font color="red">{{ Project.qa_intro| safe }}</font>

         <h3><label>Field Data Collection</label></h3>
            {{   NationalRequired.qa_field_data | safe  }}
            <font color="red">{{ Project.qa_field_data| safe }}</font>

         <h3><label>Provisional Time-Series Processing</label></h3>
            {{   NationalRequired.qa_pro_ts | safe  }}
            <font color="red">{{ Project.qa_pro_ts| safe }}</font>

         <h3><label>Approved Time-Series Data</label></h3>
            {{   NationalRequired.qa_app_ts | safe  }}
            <font color="red">{{ Project.qa_app_ts| safe }}</font>

         <h3><label>Discrete Data Processing</label></h3>
            {{   NationalRequired.qa_discrete | safe  }}
            <font color="red">{{ Project.qa_discrete| safe }}</font>

         <h3><label>Database Integrity</label></h3>
            {{   NationalRequired.qa_db_integrity | safe  }}
            <font color="red">{{ Project.qa_db_integrity| safe }}</font>

         <h3><label>Furnished Records</label></h3>
            {{   NationalRequired.qa_records | safe  }}
            <font color="red">{{ Project.qa_records| safe }}</font>

         <h3><label>Interpretive Science</label></h3>
            {{   NationalRequired.qa_interpretive | safe  }}
            <font color="red">{{ Project.qa_interpretive| safe }}</font>

         <h2><label>Training</label></h2>
            {{   NationalRequired.qa_training | safe  }}
            <font color="red">{{ Project.qa_training| safe }}</font>

         <h2><label>Terms</label></h2>
            {{   NationalRequired.qa_terms | safe  }}
            <font color="red">{{ Project.qa_terms| safe }}</font>

         <h2><label>Resources</label></h2>
            {{   NationalRequired.qa_resources | safe  }}
            <font color="red">{{ Project.qa_resources| safe }}</font>



     </div>
      </div>
  </div>



</main>
{% endblock %}

wsc/templates/wsc/index.html
{% extends "base.html" %}
{% block title %}Explore{% endblock %}
{% block content %}
{% include "includes/list.html" %}
{% endblock %}