national/blueprint.py
import os
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from app import app, db
from flask_login import login_required
from models import ACCESS, require_access, National
from national.forms import NationalEntry, NationalMaster

natl = Blueprint('national', __name__, template_folder='templates')


def get_entry_or_404(slug, author=None):
    query = National.query.filter(National.slug == slug)
    return query.first_or_404()


@natl.route('/')
def index():
    entry = National.query.filter(National.id == 1).first_or_404()
    return render_template('national/index.html', NationalRequired=entry)


@natl.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('national/detail.html', NationalRequired=entry)


@natl.route('/create/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def create():
    if request.method == 'POST':
        form = NationalMaster(request.form)
        if form.validate():
            entry = form.save_entry(National())
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % National.id, 'success')
            return redirect(url_for('index'))
    else:
        form = NationalMaster()

    return render_template('national/create.html', form=form)


@natl.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = NationalMaster(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('national.detail', slug=entry.slug))
    else:
        form = NationalMaster(obj=entry)

    return render_template('national/edit.html', NationalRequired=entry, form=form)

wsc/blueprint.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from flask_login import login_required
from app import app, db
from models import Project, National, ACCESS, require_access
from wsc.forms import ProjectEntry, ProjectApprove

wsc = Blueprint('wsc', __name__, template_folder='templates')


def get_NatlReq():
    query = National.query.filter(National.id == 1).first_or_404()
    return query


NatlReq = get_NatlReq()


def object_list(template_name, query, **context):
    object_list = query
    return render_template(template_name, object_list=object_list, **context)


def plan_list(template, query, **context):
    valid_statuses = (Project.STATUS_APPROVED, Project.STATUS_DRAFT, Project.STATUS_SUBMITTED)
    query = query.filter(Project.status.in_(valid_statuses))
    if request.args.get('q'):
        search = request.args['q']
        query = query.filter(
            (Project.body.contains(search)) |
            (Project.title.contains(search)))
    return object_list(template, query, **context)


def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Project.status == Project.STATUS_APPROVED)
    else:
        # Allow user to view their own drafts.
        query = query.filter(
            (Project.status == Project.STATUS_APPROVED) |
            ((Project.author_id == g.user) & (Project.status != Project.STATUS_DELETED)))
        return query


def get_entry_or_404(slug, author=None):
    query = Project.query.filter(Project.slug == slug)
    return query.first_or_404()


@wsc.route('/')
def index():
    plans = Project.query.order_by(Project.created_timestamp.desc())
    return render_template('/wsc/index.html', plans=plans, National=NatlReq)


@wsc.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('wsc/detail.html', Project=entry, NationalRequired=NatlReq)


@wsc.route('/create/', methods=['GET', 'POST'])
@require_access(ACCESS['WSC'])
@login_required
def create():
    if request.method == 'POST':
        form = ProjectEntry(request.form)
        if form.validate():
            entry = form.save_entry(Project(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectEntry()

    return render_template('wsc/create.html', form=form, NationalRequired=NatlReq)


@wsc.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['WSC'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = ProjectEntry(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectEntry(obj=entry)

    return render_template('wsc/edit.html', Project=entry, form=form, NationalRequired=NatlReq)


@wsc.route('/<slug>/approve/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def approve(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = ProjectApprove(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = ProjectApprove(obj=entry)

    return render_template('wsc/approve.html', Project=entry, form=form, NationalRequired=NatlReq)

templates/_macros.html
{% macro render_field(field) %}
<div class="form-group">
  <label for="{{ field.name }}">{{ field.label.text }}</label>
  {% if field.errors %}
    {{ field(class_='form-control is-invalid', **kwargs)|safe }}
    {% for error in field.errors %}
      <small style="color:red;">{{ error }}</small>
    {% endfor %}
  {% else %}
    {{ field(class_='form-control', **kwargs)|safe }}
  {% endif %}
</div>
{% endmacro %}

{% macro render_select_field(field) %}
<div class="form-group">
  <label for="{{ field.name }}">{{ field.label.text }}</label>
  {% if field.errors %}
    {{ field(class_='custom-select is-invalid', **kwargs)|safe }}
    {% for error in field.errors %}
      <small style="color:red;">{{ error }}</small>
    {% endfor %}
  {% else %}
    {{ field(class_='custom-select', **kwargs)|safe }}
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- include libraries(jQuery, bootstrap) -->


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plantain.css') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- TOC plugin CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.0/dist/bootstrap-toc.min.css">
  {% block extra_styles %}{% endblock %}


    <title>Plantain | {% block title %}{% endblock %}</title>
  </head>

  <body data-spy="scroll" data-target="#toc">
    <!-- Header -->
    {% include "navbar.html" %}

    <!-- Main content -->
    {% block content %}{% endblock %}
<br><br><br><br>
    <!-- Footer -->
    {% include "footer.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- TOC Plugin JavaScript -->
    <script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.0/dist/bootstrap-toc.min.js"></script>


  <!-- Bootstrap script for form validation -->
  <script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
  </script>
    <script>
    $(document).ready(function() {
  $('#summernote').summernote({
  height: 300,
  });
});</script>

  <!-- working on highlighting navbar links via active class -->
<!--
  <script>
  var navbarcontent = document.getElementById("navbarList");
  var links = navbarcontent.getElementsByClassName("nav-link");
  for (var i = 0; i < links.length; i++) {
    links[i].addEventListener("click", function() {
      var current = document.getElementsByClassName("active");
      current[0].className = current[0].className.replace(" active", "");
      this.className += " active";
    });
  }
  </script>
-->
  <!-- working on highlighting navbar links via active class -->
<!--
  <script>
  $('.navbar-nav .nav-link').click(function(){
      $('.navbar-nav .nav-link').removeClass('active');
      $(this).addClass('active');
  })
  </script>
-->

  <!-- highlighting navbar links via active class -->
  <script>
  $(document).ready(function() {
    $('li.active').removeClass('active');
    $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
  });
  </script>

  </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<div class="container text-center mt-5 pt-5">
  <h1 class="display-4">Contact</h1>
  <p class="lead">For help or issues, please contact...</p>
</div>
{% endblock %}

templates/explore__.html
{% extends "base.html" %}

{% block title %}Explore{% endblock %}

{% block content %}
<main>
  <div class="container">
    <!-- Explore -->
    <h1 class="text-center my-5 pt-5">Explore Plans</h1>
    <div class="input-group py-3">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      <span class="input-group-btn">
        <button class="btn btn-outline-success" type="button">Search</button>
      </span>
    </div>
    <ul class="list-group my-3">
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h5 class="mb-1"><a href="#">National Quality Assurance Plan</a></h5>
          <span class="badge badge-pill badge-success p-2">Finished</span>
        </div>
        <p class="text-muted mb-1">Office of Quality Assurance</p>
        <p class="text-muted mb-1">2018-09-01</p>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h5 class="mb-1">Quality Assurance Plan</h5>
          <span class="badge badge-pill badge-warning p-2">Started</span>
        </div>
        <p class="text-muted mb-1">Ohio-Kentucky-Indiana Quality Assurance Plan</p>
        <p class="text-muted mb-1">2018-09-14</p>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h5 class="mb-1">Quality Assurance Plan</h5>
          <span class="badge badge-pill badge-danger p-2">Not Started</span>
        </div>
        <p class="text-muted mb-1">Ohio-Kentucky-Indiana Data Management Plan</p>
        <p class="text-muted mb-1">2018-10-01</p>
      </li>
    </ul><!-- /explore -->

  </div>
</main>
    
{% endblock %}

templates/footer.html
<footer class="footer pt-1 my-md-1 pt-md-1">
  <div class="container border-top">
    <div class="row">
      <div class="col-md-5 text-left">
        <a href="https://www.usgs.gov/" title="USGS" target="_blank">
          <img class="usgs-logo" src="{{ url_for('static', filename='img/usgs.png') }}" alt="USGS" >
        </a>
      </div>
      <div class="col-md-5 text-right" >
        <span class="">
          <a class="text-muted mr-3" href="{{ url_for('about') }}">About</a>
          <a class="text-muted" href="{{ url_for('contact') }}">Contact</a>
        </span>
        </a>
      </div>
    </div>
  </div>
</footer>

templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<main>
  <!-- jumbotron -->
  <div class="jumbotron text-center" id="jumbo-grad">
    <div class="container mt-5">
      <img class="plantain-img-main" src="{{ url_for('static', filename='img/plantain.png') }}" alt="plantain"/>
      <h1 class="display-2 text-white">Plantain</h1>
      <p class="lead text-white">Maintain your science plans easily and efficiently.</p> 
    </div>
  </div><!-- /jumbotron -->

  <!-- description -->
  <div class="container py-3">
    <h3 class="text-left"><strong>Plantain builds science plans by combining national templates with user specific content.</strong></h3>
    <div class="row">
      <div class="col-md-6">
        <p class="lead text-muted">Plantain uses approved USGS national data plans as templates. Users can add specific content that gets merged with the national plan of interest. This allows users to focus more time and energy writing their specific content additions instead of on the plan in its entirety.</p>
      </div>
      <div class="col-md-6">
        <p class="lead text-muted">Plantain uses various national data plans, such as the USGS Quality Assurance Plan and the Data Mangagement Plan. Users can also view other users plans for reference and comparison.</p>
      </div>
    </div>

    <hr>

    <div class="row py-3">
      <div class="col-md-6 text-center">
        <img class="file-img" src="{{ url_for('static', filename='img/national.png') }}"  alt="national">
        <!-- <i class="fa fa-5x fa-wpforms"></i> -->
      </div>
      <div class="col-md-6">
        <h2>View National Plans</h2>
        <p class="text-muted">Plantain has various templated national plans that can be viewed including the USGS quality assurance plan and data managment plan.</p>
      </div>
    </div>

    <div class="row py-3">
      <div class="col-md-6 text-center">
        <img class="file-img" src="{{ url_for('static', filename='img/form.png') }}" alt="national">
      </div>
      <div class="col-md-6">
        <h2>Add Specific Content</h2>
        <p class="text-muted">Users fill out forms to add specific content to a national template plan of interest.</p>
      </div>
    </div>

    <div class="row py-3">
      <div class="col-md-6 text-center">
        <img class="file-img" src="{{ url_for('static', filename='img/merged.png') }}"  alt="national">
      </div>
      <div class="col-md-6">
        <h2>Merge specific content with national</h2>
        <p class="text-muted">Plantain merges user specific content into the appropriate location within the national plan.</p>
      </div>
    </div>
  </div><!-- /description -->
</main>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% from "_macros.html" import render_field, render_select_field %}

{% block title %}Log In{% endblock %}

{% block content %}
<main>
  <div class="container pt-5">
    <!-- Register Form -->
    <div class="bg-light w-50 m-5 p-5 mx-auto border">
      <img class="plantain-img-main mx-auto d-block" src="{{ url_for('static', filename='img/plantain.png') }}" alt="plantain"/>
      <h2 class="text-center m-3">Log In</h2>
      <form class="" method="POST" action="" novalidate>    
        {{ form.csrf_token }}
        {{ render_field(form.email, placeholder=form.email.label.text) }} 
        {{ render_field(form.password, placeholder=form.password.label.text) }} 
        <button type="submit" class="btn btn-success">Log In</button>
      </form>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</main>

{% endblock %}

templates/navbar.html
<header>
  <!-- navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img class="plantain-img-nav d-inline-block align-top rounded" src="{{ url_for('static', filename='img/plantain.png') }}" alt="plantain"/>
        Plantain
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto" id="navbarList">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('explore') }}">Explore</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('resources') }}">Resources</a>
          </li>
          {%  if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('national.index') }}">QAP Master Template</a>
          </li>
          {% if current_user.user_level() > 1 %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('national.create') }}">Create a Master Template</a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if current_user.user_level() > 0 %}
            <a class="nav-link" href="{{ url_for('wsc.create') }}">Create Plan</a>
            {% endif %}
          </li>
          {% endif %}
        </ul>
        
        {%  if current_user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userInfo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded=false>{{ current_user.name }}</a>
              <div class="dropdown-menu" aria-labelby="userInfo">
                <a class="dropdown-item" href="{{ url_for('index') }}">Profile</a>
                <a class="dropdown-item" href="{{ url_for('index') }}">Plans</a>
                {% if current_user.user_level() == 2 %}
                <a class="dropdown-item" href="{{ url_for('admin.index') }}">Admin</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('logout') }}" aria-disabled="true">Log Out</a>
              </div>
            </li>
          </ul>
         {% else  %}
          <a href="{{ url_for('login') }}" class="btn btn-outline-success m-2 my-sm-0" role="button" aria-disabled="true">Log In</a>
          <a href="{{ url_for('register') }}" class="btn btn-outline-success my-2 my-sm-0" role="button" aria-disabled="true">Create Account</a>
        {% endif %}

      </div>
    </div>
  </nav><!-- /navbar -->
</header>

templates/register.html
{% extends "base.html" %}
{% from "_macros.html" import render_field, render_select_field %}

{% block title %}Register{% endblock %}

{% block content %}
<main>
  <div class="container pt-5">
    <!-- Register Form -->
    <div class="bg-light w-50 m-5 p-5 mx-auto border">
      <img class="plantain-img-main mx-auto d-block" src="{{ url_for('static', filename='img/plantain.png') }}" alt="plantain"/>
      <h2 class="text-center m-3">Create an Account</h2>
      <form class="" method="POST" action="" novalidate>
        {{ form.csrf_token }}
        {{ render_field(form.email, placeholder=form.email.label.text) }} 
        {{ render_field(form.password, placeholder=form.password.label.text) }} 

        <button type="submit" class="btn btn-success">Create an account</button>
      </form>
    </div>
  </div>
</main>

{% endblock %}

templates/register_successful.html
{% extends "base.html" %}

{% block title %}Registration Successful!{% endblock %}

{% block content %}
<main>
  <div class="container pt-5">
    <div class="m-5 p-5">
      <div class="alert alert-success" role="alert">
        Registration Successful! Please log in by clicking below.
      </div>
      <a href="{{ url_for('login') }}" class="btn btn-outline-success m-2 my-sm-0" role="button" aria-disabled="true">Log In</a>
    </div>
  <div> 

</main>
{% endblock %}

templates/resources.html
{% extends "base.html" %}

{% block title %}Resources{% endblock %}

{% block content %}
<div class="container">
  <h1 class="container text-center mt-5 pt-5">Resources</h1>
  <br>
  <div class="container">
  <p class="lead">Resources from USGS - Office of Science Quality and Integrity</p>
    <ul>
      <li><a href="https://pubs.usgs.gov/of/2013/1265/">USGS Science Data Lifecycle Model</a></li>
      <li><a href="https://www.usgs.gov/products/data-and-tools/data-management/">USGS Data Management Website</a></li>
      <li><a href="https://www.usgs.gov/about/organization/science-support/science-quality-and-integrity/fundamental-science-practices">FSP Policies</a></li>
      <li><a href="https://pubs.er.usgs.gov/publication/ofr20161202">Policies and practices for publishing data on ScienceBase </a></li>
      <li><a href="https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/data-release-workbench">USGS Data Release Workbench</a></li>
    </ul>
  </div>
</div>

{% endblock %}

templates/results.html
{% extends "base.html" %}

{% block title %}Results{% endblock %}

{% block content %}
<main>
  <div class="container">
    <h1 class="text-center my-5 pt-5">Email: {{ email }}</h1>
    <h1 class="text-center my-5 pt-5">Password: {{ password }}</h1>
    <h1 class="text-center my-5 pt-5">WSC: {{ wsc }}</h1>
  </div>
</main>

{% endblock %}