national/forms.py
import wtforms
from wtforms import StringField
from wtforms.validators import DataRequired, Optional
from flask_ckeditor import CKEditorField
import bleach

from models import NationalRequired, National


class NationalEntry(wtforms.Form):

    title = StringField(
        'Introduction',
        validators=[DataRequired()])

    intro = CKEditorField(
        'Introduction',
        validators=[DataRequired()])

    scope = CKEditorField(
        'Scope',
        validators=[DataRequired()])

    org = CKEditorField(
        'Organization',
        validators=[DataRequired()])

    resp = CKEditorField(
        'Responsibilities',
        validators=[DataRequired()])

    status = wtforms.SelectField(
        'Status',
        choices=(
            (NationalRequired.STATUS_DRAFT, "Save Draft"),
            (NationalRequired.STATUS_SUBMITTED, "Submit for Review"),
            (NationalRequired.STATUS_APPROVED, "Approve and Publish")),
        coerce=int)

    def save_entry(self, NationalRequired):
        self.populate_obj(NationalRequired)
        NationalRequired.generate_slug()
        return NationalRequired


class NationalMaster(wtforms.Form):
    title = StringField(
        'Introduction',
        validators=[DataRequired()])

    intro = CKEditorField(
        'Introduction',
        validators=[Optional()])

    scope = CKEditorField(
        'Scope',
        validators=[Optional()])

    org = CKEditorField(
        'Organization',
        validators=[Optional()])

    resp = CKEditorField(
        'Responsibilities',
        validators=[Optional()])

    facilities = CKEditorField(
        'Facilities',
        validators=[Optional()])

    labs = CKEditorField(
        'Laboratories',
        validators=[Optional()])

    dq_management = CKEditorField(
        'Data-Quality Management',
        validators=[Optional()])

    dq_planning = CKEditorField(
        'Data-Quality Planning',
        validators=[Optional()])

    dq_roles = CKEditorField(
        'Data-Quality Roles',
        validators=[Optional()])

    dq_workflows = CKEditorField(
        'Data-Quality Workflows',
        validators=[Optional()])

    dq_wf_pro = CKEditorField(
        'wf proposals',
        validators=[Optional()])

    dq_wf_workplan = CKEditorField(
        'wf workplans',
        validators=[Optional()])

    dq_wf_project_dmp = CKEditorField(
        'proj data management',
        validators=[Optional()])

    dq_wf_review = CKEditorField(
        'proj reviews',
        validators=[Optional()])

    dq_datasharing = CKEditorField(
        'Data Sharing Agreements',
        validators=[Optional()])

    dq_mous = CKEditorField(
        'Memoranda of Understands (MOUs)',
        validators=[Optional()])

    dq_access = CKEditorField(
        'Access Controls and Copyrights',
        validators=[Optional()])

    dq_aquisition = CKEditorField(
        'Data Acquisitions',
        validators=[Optional()])

    dq_aqu_roles = CKEditorField(
        'Data Acquisitions Roles',
        validators=[Optional()])

    dq_aqu_proc = CKEditorField(
        'Data Acquisitions Procedure',
        validators=[Optional()])

    dq_aqu_proc_coll = CKEditorField(
        'Data Acquisitions Collection Procedure',
        validators=[Optional()])

    dq_aqu_proc_proc = CKEditorField(
        'Data Acquisitions Processing Policies',
        validators=[Optional()])

    dq_aqu_proc_anal = CKEditorField(
        'Data Analysis and Policies',
        validators=[Optional()])

    dq_doc = CKEditorField(
        'Data Documentation',
        validators=[Optional()])

    dq_format = CKEditorField(
        'Data Formats',
        validators=[Optional()])

    dq_org = CKEditorField(
        'Organization of Files or Data',
        validators=[Optional()])

    dq_store = CKEditorField(
        'Data Storage',
        validators=[Optional()])

    dq_store_roles = CKEditorField(
        'Storage Roles',
        validators=[Optional()])

    dq_store_repo = CKEditorField(
        'Repositories',
        validators=[Optional()])

    dq_store_archive = CKEditorField(
        'Archiving',
        validators=[Optional()])

    dq_pubs = CKEditorField(
        'Publication and Sharing',
        validators=[Optional()])

    dq_pubs_roles = CKEditorField(
        'Publication Roles',
        validators=[Optional()])

    dq_pubs_workflow = CKEditorField(
        'Publication Workflow',
        validators=[Optional()])

    dq_pubs_prop = CKEditorField(
        'Publication Sensitive Data',
        validators=[Optional()])

    dq_pubs_release = CKEditorField(
        'Publication release',
        validators=[Optional()])

    dq_pubs_cite = CKEditorField(
        'Publication Citation',
        validators=[Optional()])

    dq_pubs_doi = CKEditorField(
        'Publication DOI',
        validators=[Optional()])

    dq_pubs_meta = CKEditorField(
        'Publication Meta',
        validators=[Optional()])

    dq_pubs_catalog = CKEditorField(
        'Publication Catalog',
        validators=[Optional()])

    qa_intro = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_field_data = CKEditorField(
        'Quality Assessment - Field Data',
        validators=[Optional()])

    qa_pro_ts = CKEditorField(
        'Quality Assessment - Time series Provisional',
        validators=[Optional()])

    qa_app_ts = CKEditorField(
        'Quality Assessment - Time Series Approved',
        validators=[Optional()])

    qa_discrete = CKEditorField(
        'Quality Assessment - Discrete Data Processing',
        validators=[Optional()])

    qa_db_integrity = CKEditorField(
        'Quality Assessment - Databases',
        validators=[Optional()])

    qa_records = CKEditorField(
        'Quality Assessment - records',
        validators=[Optional()])

    qa_interpretive = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_training = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_terms = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    qa_resources = CKEditorField(
        'Quality Assessment',
        validators=[Optional()])

    status = wtforms.SelectField(
        'Status',
        choices=(
            (NationalRequired.STATUS_DRAFT, "Save Draft"),
            (NationalRequired.STATUS_SUBMITTED, "Submit for Review"),
            (NationalRequired.STATUS_APPROVED, "Approve and Publish")),
        coerce=int)


    def save_entry(self, NationalRequired):
        self.populate_obj(NationalRequired)
        NationalRequired.generate_slug()
        return NationalRequired

National/blueprint.py
import os
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from app import app, db
from flask_login import login_required
from models import NationalRequired, ACCESS, require_access
from National.forms import NationalEntry

natl = Blueprint('National', __name__, template_folder='templates')


def get_entry_or_404(slug, author=None):
    query = NationalRequired.query.filter(NationalRequired.slug == slug)
    return query.first_or_404()


@natl.route('/')
def index():
    entry = NationalRequired.query.filter(NationalRequired.id == 1).first_or_404()
    return render_template('National/index.html', NationalRequired=entry)


@natl.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('National/detail.html', NationalRequired=entry)


@natl.route('/create/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def create():
    if request.method == 'POST':
        form = NationalEntry(request.form)
        if form.validate():
            entry = form.save_entry(NationalRequired())
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % NationalRequired.id, 'success')
            return redirect(url_for('index'))
    else:
        form = NationalEntry()

    return render_template('National/create.html', form=form)


@natl.route('/<slug>/edit', methods=['GET','POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = NationalEntry(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('wsc.detail', slug=entry.slug))
    else:
        form = NationalEntry(obj=entry)

    return render_template('National/edit.html', NationalRequired=entry, form=form)

national/blueprint.py
import os
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from app import app, db
from flask_login import login_required
from models import ACCESS, require_access, National
from national.forms import NationalEntry, NationalMaster

natl = Blueprint('national', __name__, template_folder='templates')


def get_entry_or_404(slug, author=None):
    query = National.query.filter(National.slug == slug)
    return query.first_or_404()


@natl.route('/')
def index():
    entry = National.query.filter(National.id == 1).first_or_404()
    return render_template('national/index.html', NationalRequired=entry)


@natl.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('national/detail.html', NationalRequired=entry)


@natl.route('/create/', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def create():
    if request.method == 'POST':
        form = NationalMaster(request.form)
        if form.validate():
            entry = form.save_entry(National())
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % National.id, 'success')
            return redirect(url_for('index'))
    else:
        form = NationalMaster()

    return render_template('national/create.html', form=form)


@natl.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
@require_access(ACCESS['ADMIN'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = NationalMaster(request.form, obj=entry)
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" update.' % entry.title, 'success')
        return redirect(url_for('national.detail', slug=entry.slug))
    else:
        form = NationalMaster(obj=entry)

    return render_template('national/edit.html', NationalRequired=entry, form=form)

national/templates/national/detail.html
{% extends "base.html" %}

{% block title %}{{ NationalRequired.slug }}{% endblock %}

{% block content_title %}{{ NationalRequired.slug }}{% endblock %}



{% block content %}
<main>
  <div class="container pt-5">
      <div class="row pt-5">
      <!-- sidebar -->
      <div class="col-sm-3">
        <nav id="toc" data-toggle="toc" class="sticky-top">
          <h5 class="text-muted">Table of Contents</h5>
        </nav>
      </div>
        <!-- main -->
     <div class="col-lg">
         <h1>{{ NationalRequired.title }}</h1>
        <h2><label>Introduction</label></h2>
            {{  NationalRequired.intro | safe }}


         <h2><label>Organization</label></h2>
            {{  NationalRequired.org  | safe}}


         <h2><label>Responsibilities</label></h2>
            {{  NationalRequired.resp  | safe }}


         <h2><label>Facilities</label></h2>
            {{   NationalRequired.facilities | safe  }}


         <h2><label>Laboratories</label></h2>
             {{   NationalRequired.labs | safe  }}


         <h2><label>Data-Quality Management</label></h2>
            {{   NationalRequired.dq_management | safe  }}


         <h3><label>Planning</label></h3>
            {{   NationalRequired.dq_planning | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_roles | safe  }}


         <h4><label>Workflows</label></h4>
            {{   NationalRequired.dq_workflows | safe  }}


         <h5><label>Proposals</label></h5>
            {{   NationalRequired.dq_wf_pro | safe  }}


         <h5><label>Workplans</label></h5>
            {{   NationalRequired.dq_wf_workplan | safe  }}


         <h5><label>Project Data Management Plans</label></h5>
            {{   NationalRequired.dq_wf_project_dmp | safe  }}


         <h5><label>Project Reviews</label></h5>
            {{   NationalRequired.dq_wf_review | safe  }}


         <h4><label>Data Sharing Agreements</label></h4>
            {{   NationalRequired.dq_datasharing | safe  }}


         <h4><label>Memoranda of Understanding (MOUs)</label></h4>
            {{   NationalRequired.dq_mous | safe  }}


         <h4><label>Access Controls/Copyright</label></h4>
            {{   NationalRequired.dq_access | safe  }}


         <h3><label>Data Acquisition, Processing and Analysis</label></h3>
            {{   NationalRequired.dq_aquisition | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_aqu_roles | safe  }}


        <h4><label>Procedures and Methods</label></h4>
            {{   NationalRequired.dq_aqu_proc | safe  }}


         <h5><label>Data Collection Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_coll | safe  }}


          <h5><label>Data Processing Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_proc | safe  }}


          <h5><label>Data Analysis Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_anal | safe  }}


          <h4><label>Documentation</label></h4>
            {{   NationalRequired.dq_doc | safe  }}


         <h4><label>Data Formats</label></h4>
            {{   NationalRequired.dq_format | safe  }}


         <h4><label>Organization of Files/Data</label></h4>
            {{   NationalRequired.dq_org | safe  }}


         <h3><label>Data Preservation, Storage and Archive</label></h3>
            {{   NationalRequired.dq_store | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_store_roles | safe  }}


         <h4><label>Repositories</label></h4>
            {{   NationalRequired.dq_store_repo | safe  }}


         <h4><label>Archiving</label></h4>
            {{   NationalRequired.dq_store_archive | safe  }}


         <h3><label>Publication/Sharing</label></h3>
            {{   NationalRequired.dq_pubs | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_pubs_roles | safe  }}


         <h4><label>Workflow</label></h4>
            {{   NationalRequired.dq_pubs_workflow | safe  }}


         <h4><label>Proprietary and Sensitive Data</label></h4>
            {{   NationalRequired.dq_pubs_prop | safe  }}


         <h4><label>Dissemination/Release</label></h4>
            {{   NationalRequired.dq_pubs_release | safe  }}

         <h4><label>Data Citation</label></h4>
            {{   NationalRequired.dq_pubs_cite | safe  }}


         <h4><label>Digital Object Identifiers</label></h4>
            {{   NationalRequired.dq_pubs_doi | safe  }}


         <h4><label>Metadata/Documentation</label></h4>
            {{   NationalRequired.dq_pubs_meta | safe  }}

         <h4><label>Data Catalogs</label></h4>
            {{   NationalRequired.dq_pubs_catalog | safe  }}


         <h2><label>Quality Assessment</label></h2>
            {{   NationalRequired.qa_intro | safe  }}


         <h3><label>Field Data Collection</label></h3>
            {{   NationalRequired.qa_field_data | safe  }}


         <h3><label>Provisional Time-Series Processing</label></h3>
            {{   NationalRequired.qa_pro_ts | safe  }}


         <h3><label>Approved Time-Series Data</label></h3>
            {{   NationalRequired.qa_app_ts | safe  }}


         <h3><label>Discrete Data Processing</label></h3>
            {{   NationalRequired.qa_discrete | safe  }}


         <h3><label>Database Integrity</label></h3>
            {{   NationalRequired.qa_db_integrity | safe  }}


         <h3><label>Furnished Records</label></h3>
            {{   NationalRequired.qa_records | safe  }}

         <h3><label>Interpretive Science</label></h3>
            {{   NationalRequired.qa_interpretive | safe  }}


         <h2><label>Training</label></h2>
            {{   NationalRequired.qa_training | safe  }}


         <h2><label>Terms</label></h2>
            {{   NationalRequired.qa_terms | safe  }}


         <h2><label>Resources</label></h2>
            {{   NationalRequired.qa_resources | safe  }}

     </div>
      </div>
  </div>

</main>
{% endblock %}

national/templates/national/index.html
{% extends "base.html" %}

{% block title %}{{ NationalRequired.slug }}{% endblock %}

{% block content_title %}{{ NationalRequired.slug }}{% endblock %}



{% block content %}
<main>
  <div class="container pt-5">
      <div class="row pt-5">
      <!-- sidebar -->
      <div class="col-sm-3">
        <nav id="toc" data-toggle="toc" class="sticky-top">
          <h5 class="text-muted">Table of Contents</h5>
        </nav>
        <br>
          <a href="{{ url_for('national.edit', slug=NationalRequired.slug) }}">Edit</a></p>
      </div>
        <!-- main -->
     <div class="col-lg">
         <h1>{{ NationalRequired.title }}</h1>
        <h2><label>Introduction</label></h2>
            {{  NationalRequired.intro | safe }}


         <h2><label>Organization</label></h2>
            {{  NationalRequired.org  | safe}}


         <h2><label>Responsibilities</label></h2>
            {{  NationalRequired.resp  | safe }}


         <h2><label>Facilities</label></h2>
            {{   NationalRequired.facilities | safe  }}


         <h2><label>Laboratories</label></h2>
             {{   NationalRequired.labs | safe  }}


         <h2><label>Data-Quality Management</label></h2>
            {{   NationalRequired.dq_management | safe  }}


         <h3><label>Planning</label></h3>
            {{   NationalRequired.dq_planning | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_roles | safe  }}


         <h4><label>Workflows</label></h4>
            {{   NationalRequired.dq_workflows | safe  }}


         <h5><label>Proposals</label></h5>
            {{   NationalRequired.dq_wf_pro | safe  }}


         <h5><label>Workplans</label></h5>
            {{   NationalRequired.dq_wf_workplan | safe  }}


         <h5><label>Project Data Management Plans</label></h5>
            {{   NationalRequired.dq_wf_project_dmp | safe  }}


         <h5><label>Project Reviews</label></h5>
            {{   NationalRequired.dq_wf_review | safe  }}


         <h4><label>Data Sharing Agreements</label></h4>
            {{   NationalRequired.dq_datasharing | safe  }}


         <h4><label>Memoranda of Understanding (MOUs)</label></h4>
            {{   NationalRequired.dq_mous | safe  }}


         <h4><label>Access Controls/Copyright</label></h4>
            {{   NationalRequired.dq_access | safe  }}


         <h3><label>Data Acquisition, Processing and Analysis</label></h3>
            {{   NationalRequired.dq_aquisition | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_aqu_roles | safe  }}


        <h4><label>Procedures and Methods</label></h4>
            {{   NationalRequired.dq_aqu_proc | safe  }}


         <h5><label>Data Collection Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_coll | safe  }}


          <h5><label>Data Processing Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_proc | safe  }}


          <h5><label>Data Analysis Procedures and Policies</label></h5>
            {{   NationalRequired.dq_aqu_proc_anal | safe  }}


          <h4><label>Documentation</label></h4>
            {{   NationalRequired.dq_doc | safe  }}


         <h4><label>Data Formats</label></h4>
            {{   NationalRequired.dq_format | safe  }}


         <h4><label>Organization of Files/Data</label></h4>
            {{   NationalRequired.dq_org | safe  }}


         <h3><label>Data Preservation, Storage and Archive</label></h3>
            {{   NationalRequired.dq_store | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_store_roles | safe  }}


         <h4><label>Repositories</label></h4>
            {{   NationalRequired.dq_store_repo | safe  }}


         <h4><label>Archiving</label></h4>
            {{   NationalRequired.dq_store_archive | safe  }}


         <h3><label>Publication/Sharing</label></h3>
            {{   NationalRequired.dq_pubs | safe  }}


         <h4><label>Roles and Responsibilities</label></h4>
            {{   NationalRequired.dq_pubs_roles | safe  }}


         <h4><label>Workflow</label></h4>
            {{   NationalRequired.dq_pubs_workflow | safe  }}


         <h4><label>Proprietary and Sensitive Data</label></h4>
            {{   NationalRequired.dq_pubs_prop | safe  }}


         <h4><label>Dissemination/Release</label></h4>
            {{   NationalRequired.dq_pubs_release | safe  }}

         <h4><label>Data Citation</label></h4>
            {{   NationalRequired.dq_pubs_cite | safe  }}


         <h4><label>Digital Object Identifiers</label></h4>
            {{   NationalRequired.dq_pubs_doi | safe  }}


         <h4><label>Metadata/Documentation</label></h4>
            {{   NationalRequired.dq_pubs_meta | safe  }}

         <h4><label>Data Catalogs</label></h4>
            {{   NationalRequired.dq_pubs_catalog | safe  }}


         <h2><label>Quality Assessment</label></h2>
            {{   NationalRequired.qa_intro | safe  }}


         <h3><label>Field Data Collection</label></h3>
            {{   NationalRequired.qa_field_data | safe  }}


         <h3><label>Provisional Time-Series Processing</label></h3>
            {{   NationalRequired.qa_pro_ts | safe  }}


         <h3><label>Approved Time-Series Data</label></h3>
            {{   NationalRequired.qa_app_ts | safe  }}


         <h3><label>Discrete Data Processing</label></h3>
            {{   NationalRequired.qa_discrete | safe  }}


         <h3><label>Database Integrity</label></h3>
            {{   NationalRequired.qa_db_integrity | safe  }}


         <h3><label>Furnished Records</label></h3>
            {{   NationalRequired.qa_records | safe  }}

         <h3><label>Interpretive Science</label></h3>
            {{   NationalRequired.qa_interpretive | safe  }}


         <h2><label>Training</label></h2>
            {{   NationalRequired.qa_training | safe  }}


         <h2><label>Terms</label></h2>
            {{   NationalRequired.qa_terms | safe  }}


         <h2><label>Resources</label></h2>
            {{   NationalRequired.qa_resources | safe  }}

     </div>
      </div>
  </div>


</main>
{% endblock %}